#management.endpoints.web.exposure.include=*
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
    port: 8090

    
course:
 message: hola desde aplication inicial
 defaultMessage: mensaje vacio

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
   
 


 
